apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: categorizer
  namespace: abuse-api-dev
  labels:
    app: categorizer
spec:
  schedule: "0 */1 * * *"

  # Deadline in seconds for starting the job if it misses its scheduled time.
  startingDeadlineSeconds: 60

  # The cron job does not allow concurrent runs
  # if it is time for a new job run and the previous job run hasn't finished yet, the cron job skips the new job run
  concurrencyPolicy: Forbid

  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: categorizer
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: dcu-artifactory-creds
          volumes:
            - name: categorizer-ssl
              secret:
                secretName: tls-categorizer
          containers:
            - name: categorizer
              imagePullPolicy: Always
              image: docker-dcu-local.artifactory.secureserver.net/categorizer:dev
              volumeMounts:
                - mountPath: "/etc/categorizer/ssl"
                  name: categorizer-ssl
                  readOnly: true
              env:
                - name: sysenv
                  value: dev
                - name: BUILD_DATE
                  value: THIS_STRING_IS_REPLACED_DURING_BUILD
                - name: LOG_CFG
                  value: logging.yaml
                - name: CATEGORIZER_KEY
                  value: /etc/categorizer/ssl/tls.key
                - name: CATEGORIZER_CERT
                  value: /etc/categorizer/ssl/tls.crt
                - name: IRIS_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: db-categorizer
                      key: username
                - name: IRIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-categorizer
                      key: password
                - name: CATEGORIZER_USER
                  valueFrom:
                    secretKeyRef:
                      name: auth-categorizer
                      key: username
                - name: CATEGORIZER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: auth-categorizer
                      key: password