apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: categorizer
  namespace: abuse-api-prod
  labels:
    app: categorizer
spec:
  schedule: "0 */1 * * *"

  # Deadline in seconds for starting the job if it misses its scheduled time.
  startingDeadlineSeconds: 60

  # The cron job does not allow concurrent runs
  # if it is time for a new job run and the previous job run hasn't finished yet, the cron job skips the new job run
  concurrencyPolicy: Forbid

  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: categorizer
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: dcu-artifactory-creds

          containers:
            - name: categorizer
              imagePullPolicy: Always
              image: docker-dcu-local.artifactory.secureserver.net/categorizer:REPLACE_WITH_GIT_COMMIT
              env:
                - name: sysenv
                  value: prod
                - name: BUILD_DATE
                  value: THIS_STRING_IS_REPLACED_DURING_BUILD
                - name: LOG_CFG
                  value: logging.yaml

                - name: IRIS_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: db-categorizer
                      key: username
                - name: IRIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-categorizer
                      key: password